spring:
#  resources:
#    static-locations: classpath:/static/
  datasource:
    #连接MySQL
    url: jdbc:mysql://localhost:3306/machines?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: Kenn5666225.
    driver-class-name: com.mysql.cj.jdbc.Driver


#mybatis:
#  typeAliasesPackage: com.biao.entity
#  mapper-locations: classpath:mapper/*.xml
#  configuration:
#     #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
#     map-underscore-to-camel-case: true

   #打印SQL信息
#logging:
#  level:
#   com:
#    liepin:
#      controller: DEBUG
#      dao: DEBUG

server:
  port: 8080



